
dist: trusty
sudo: required

language: c
# git submodules workaround
git:
  submodules: false
# use sed to replace SSH URL with the public URL, then init submodules 
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install doxygen graphviz gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
  - sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30
  - sudo update-alternatives --set cc /usr/bin/gcc
  - sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30
  - sudo update-alternatives --set c++ /usr/bin/g++
compiler:
  - gcc
env:
  - BUILD_KERNEL=4.4.0-75-generic
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpcap-dev libpci-dev libsndfile1-dev libjack-dev linux-headers-4.4.0-75-generic
  - sudo apt-get install -y libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev libasound2-dev
  - sudo apt-get install -y python3-pip
  - curl -L "https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip"  -o ninja-linux.zip
  - sudo unzip ninja-linux.zip -d /usr/local/bin
  - sudo chmod 755 /usr/local/bin/ninja
  - sudo pip3 install meson
  - curl -L "https://cmocka.org/files/1.1/cmocka-1.1.1.tar.xz" -o cmocka-1.1.1.tar.xz
  - tar -xf cmocka-1.1.1.tar.xz
  - pushd cmocka-1.1.1
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - sudo make install
  - popd
  - sudo cp /usr/src/linux-headers-4.4.0-75/include/uapi/linux/if_ether.h /usr/include/linux
  - sudo cp /usr/src/linux-headers-4.4.0-75/include/uapi/linux/ethtool.h /usr/include/linux
  - sudo cp /usr/src/linux-headers-4.4.0-75/include/uapi/linux/ptp_clock.h /usr/include/linux
  - CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.4-Linux-x86_64.tar.gz"
  - mkdir -p ${TRAVIS_BUILD_DIR}/deps/cmake
  - travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${TRAVIS_BUILD_DIR}/deps/cmake
  - export PATH=${TRAVIS_BUILD_DIR}/deps/cmake/bin:${PATH}


script: ./travis.sh

